apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: red-hat-design-system
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/bepowers-tenant/red-hat-design-system/red-hat-design-system@sha256:55301739c371cf4cded8b8d9383bfacc265df212fde9255528c4ecc6237bee40
        name: my-nodejs
        resources: {}
status: {}
